### ISSUE TITLE
Suboptimal performance with TCP over high bandwidth networks

### ISSUE THREAD

**Issue by cswinter** [NVIDIA/nccl#209] opened 2019-04-19 23:37 UTC
Hi! Many thanks for creating a great framework. NCCL is widely used at our org for scaling the training of ML models and has proved very reliable.

I am currently trying to figure out how to achieve optimal inter-node performance with NCCL running over TCP on high bandwidth networks (32Gpbs, 100Gpbs, and higher). Even with large message sizes we have not been able to reliably obtain more than 60% of wire speed over 32Gpbs networks (see below for nccl-tests output). From what I've gathered NCCL just hasn't been fully optimized for this configuration yet (although I'm still holding out some hope that I'm just doing it wrong 😄).

I'm prepared to work fulltime for several weeks on lifting any limitations in the current implementation but I could use a few pointers for getting started. Do you have a sense for what the most promising changes might be and how to incorporate them into the codebase? One thing I might want to explore is using multiple threads/TCP streams. But there is still scope to better utilize a single TCP stream as well so maybe there are some simpler optimizations to try first?

I've been looking into the codebase and there's a number of things that I don't really understand yet:
- Running nccl-tests `all_reduce_perf -w 0 -n 1`  seems to spawn a total of 4 allreduce ops according to my `TRACE` output. I would have expected just 2 (on for in-place one for out-of-place).
- I'm not super clear on the control flow/threading model. In my tests NCCL is using exactly two cores, some of main files of interest seem to be `net_socket.cc`, `net.cc`, `socket.h`, `enqueue.cc` and a lot of cycles are spent polling `ncclSocketIrecv`/`ncclSocketIsend` but I'm still struggling with how everything fits together and exactly where/how the actual network transfers happen.

Some more details on my setup. My current config consists of two GCE machines with 8xV100, plenty of cores/RAM and 32Gbps network (no RDMA). I get about 28Gbps bidirectional bandwidth by running one `iperf3` server and client on each node (and >30Gpbs with `-Z -P4` flags). Anecdotally, more complex setups that include Horovod have occasionally been able to hit 60% of wire speed on 32Gbps and 50Gbps networks. In this case, running nccl-tests only yields 16Gpbs:
```
root@managed-worker-l83z:/# mpirun --allow-run-as-root -H 10.73.0.52:1,10.73.0.15:1 -np 2 -mca btl_tcp_if_include ens12 -x NCCL_IB_DISABLE=1 -x LD_LIBRARY_PATH -x NCCL_SOCKET_IFNAME=ens12 -x NCCL_DEBUG=INFO /nccl-tests/build/all_reduce_perf -b 1G -e 1G -f 2 -g 1 -c 0
# nThread 1 nGpus 1 minBytes 1073741824 maxBytes 1073741824 step: 2(factor) warmup iters: 5 iters: 20 validation: 0
#
# Using devices
#   Rank  0 Pid     51 on managed-worker-l83z device  0 [0x00] Tesla V100-SXM2-16GB
#   Rank  1 Pid     73 on managed-worker-jbk7 device  0 [0x00] Tesla V100-SXM2-16GB
managed-worker-l83z:51:51 [0] NCCL INFO NET/Socket : Using [0]ens12:10.73.0.52<0>
managed-worker-l83z:51:51 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).
managed-worker-l83z:51:51 [0] NCCL INFO NCCL_IB_DISABLE set by environment to 1.
NCCL version 2.4.2+cuda10.0
managed-worker-jbk7:73:73 [0] NCCL INFO NET/Socket : Using [0]ens12:10.73.0.15<0>
managed-worker-jbk7:73:73 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).
managed-worker-jbk7:73:73 [0] NCCL INFO NCCL_IB_DISABLE set by environment to 1.
managed-worker-l83z:51:57 [0] NCCL INFO Setting affinity for GPU 0 to 010000,00000001
managed-worker-l83z:51:57 [0] NCCL INFO comm 0x7fd518002560 rank 0 nranks 2 cudaDev 0 nvmlDev 0
managed-worker-jbk7:73:78 [0] NCCL INFO Setting affinity for GPU 0 to 010000,00000001
managed-worker-jbk7:73:78 [0] NCCL INFO comm 0x7f9be0002560 rank 1 nranks 2 cudaDev 0 nvmlDev 0
managed-worker-l83z:51:57 [0] NCCL INFO CUDA Dev 0[0], Socket NIC distance :  PHB
managed-worker-jbk7:73:78 [0] NCCL INFO CUDA Dev 0[0], Socket NIC distance :  PHB
managed-worker-l83z:51:57 [0] NCCL INFO Channel 00 :    0   1
managed-worker-l83z:51:57 [0] NCCL INFO Channel 01 :    0   1
managed-worker-jbk7:73:78 [0] NCCL INFO Ring 00 : 0 -> 1 [receive] via NET/Socket/0
managed-worker-l83z:51:57 [0] NCCL INFO Ring 00 : 1 -> 0 [receive] via NET/Socket/0
managed-worker-jbk7:73:78 [0] NCCL INFO Ring 00 : 1 -> 0 [send] via NET/Socket/0
managed-worker-l83z:51:57 [0] NCCL INFO Ring 00 : 0 -> 1 [send] via NET/Socket/0
managed-worker-l83z:51:57 [0] NCCL INFO Ring 01 : 1 -> 0 [receive] via NET/Socket/0
managed-worker-jbk7:73:78 [0] NCCL INFO Ring 01 : 0 -> 1 [receive] via NET/Socket/0
managed-worker-l83z:51:57 [0] NCCL INFO Ring 01 : 0 -> 1 [send] via NET/Socket/0
managed-worker-jbk7:73:78 [0] NCCL INFO Ring 01 : 1 -> 0 [send] via NET/Socket/0
managed-worker-l83z:51:57 [0] NCCL INFO Using 256 threads, Min Comp Cap 7, Trees disabled
managed-worker-l83z:51:57 [0] NCCL INFO comm 0x7fd518002560 rank 0 nranks 2 cudaDev 0 nvmlDev 0 - Init COMPLETE
managed-worker-jbk7:73:78 [0] NCCL INFO comm 0x7f9be0002560 rank 1 nranks 2 cudaDev 0 nvmlDev 0 - Init COMPLETE
#
#                                                     out-of-place                       in-place
#       size         count    type   redop     time   algbw   busbw  error     time   algbw   busbw  error
#        (B)    (elements)                     (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)
managed-worker-l83z:51:51 [0] NCCL INFO Launch mode Parallel
  1073741824     268435456   float     sum   539383    1.99    1.99    N/A   553087    1.94    1.94    N/A
managed-worker-l83z:51:51 [0] NCCL INFO Destroyed comm 0x7fd518002560 rank 0
managed-worker-jbk7:73:73 [0] NCCL INFO Destroyed comm 0x7f9be0002560 rank 1
# Out of bounds values : 0 OK
# Avg bus bandwidth    : 1.96602
#
```

**Comment by AddyLaddy** [comment] 2019-04-19 23:43
We are currently investigating NCCL over TCP performance in cloud environments. It would be interesting to see what performance you can get with NCCL 2.3.7 and also by setting NCCL_MIN_NRINGS to various values from 1 to 8

**Comment by AddyLaddy** [comment] 2019-04-19 23:47
The reason -w0 -n1 issues more that just one operation is that you would also need to disable data checking with -c0
Also, NCCL always does at least 2 calls for in-place and out-of-place buffers for each message size.

**Comment by cswinter** [comment] 2019-04-19 23:53
I've tried varying `NCCL_MIN_NRINGS` before and it didn't seem to make a huge difference but let me get you some actual numbers of that and 2.3.7.

**Comment by cswinter** [comment] 2019-04-20 00:44
Much better perf on 2.3.7, close to optimal with 8 rings! Might try it out on 100Gbps network as well next week.

NCCL 2.4.2-1+cuda10.0, nccl-tests@cbe7f65 

| rings | bw / GB/s |
| --- | --- |
| 1 | 1.85 |
| 2 | 1.95 |
| 4 | 1.73 |
| 8 | 1.45 |

NCCL 2.3.7-1+cuda10.0, nccl-tests@dcf8189

| rings | bw / GB/s |
| --- | --- |
| 1 | 2.06 |
| 2 | 2.77 |
| 4 | 3.28 |
| 8 | 3.75 |

For 2.3.7, bw is from in-place (always slightly faster than out-of-place) and for 2.4.2 out-of-place (always slightly faster than in-place).

Full nccl-tests output: [2.3.7](https://gist.github.com/cswinter/220e2360c8014e031186fecf9d79ba1b), [2.4.2](https://gist.github.com/cswinter/6193721676f6a7903cca74ad660db975)

**Comment by AddyLaddy** [comment] 2019-04-20 01:42
Great news! Thanks for those figures. 100Gbps figures would be very interesting to us too.

We are aware of the NCCL over Sockets regression going from NCCL 2.3.7 to NCCL 2.4.x and are actively working on a fix.
Hopefully we can push out a PR for you to try once the code has been fully tested and inspected.

**Comment by kwen2501** [comment] 2019-04-26 23:30
We're actively working on it, we hope we'll be able to provide something functional by end of month and fix the issues within the next month.

We are also working on a better solution that would not require to increase rings. But that would need a bit more work.

**Comment by yaroslavvb** [comment] 2019-04-29 18:43
I'm seeing the same issue on AWS, I get get 50 Gbps between two machines using NCCL 2.3.7 with 16 rings, but upgrading to NCCL 2.4.6 drops by network utilization to under 10 Gbps (this is expected when using a single ring)

**Comment by kwen2501** [comment] 2019-05-10 23:55
Hi @cswinter, @yaroslavvb and others, thanks for your patience. 

Here is a first version of the fix.  It should achieve up to 8-10 GB/s on AWS (between two P3dn nodes), even without setting `NCCL_MIN_NRINGS`.

Two environment variables have been added for tuning the socket transport performance:
- `NCCL_SOCKET_NTHREADS`: number of CPU threads used per rank-to-rank connection over the TCP network.
- `NCCL_NSOCKS_PERTHREAD`: number of TCP sockets driven by each CPU thread.

You can use those two environment variables to increase the total number of sockets per network connection in the NCCL ring (the total number being `NCCL_SOCKET_NTHREADS` x `NCCL_NSOCKS_PERTHREAD`). Hence, **there should be no more need to increase `NCCL_MIN_NRINGS` from its default value.** 

**Note**: there is no need to set `NCCL_NSOCKS_PERTHREAD` and `NCCL_SOCKET_NTHREADS` on AWS as we auto tune them already. In other cases, the default values for those two environment variables are 1, but you can tune them based on your network speed, etc.

Known issue: the CPU utilization is yet to be improved. We will continue to improve it, just posting the PR now to unblock you.

**Comment by cswinter** [comment] 2019-05-11 00:50
Awesome, great to see this move along! I ran some quick tests on a GCE machine where `iperf -c x.x.x.x -P4 -d` achieves 32Gbps and haven't see any improvements so far. Increasing `NCCL_SOCKET_NTHREADS` seems to decrease performance, e.g. with`NCCL_SOCKET_NTHREADS=4`: https://gist.github.com/cswinter/3bc2cbcc7c947e4a2736188dd6e74240

Didn't yet try very hard getting it to work though and it looks like just two cores are being used so I'm probably still doing something wrong.

**Comment by kwen2501** [comment] 2019-05-11 03:31
@cswinter Thanks for the feedback!

We have a few questions (just trying to figure out how to improve it):
- What is your MPI binding strategy? Since threads need to be spawned for driving the sockets, would setting `--bind-to none` help here?
- Have you tried increasing `NCCL_NSOCKS_PERTHREAD`? (It is fine if you haven't, just trying to see if there are more data points)
- The 1-GPU-per-node case may not be a good reflection of the network bandwidth. But as you mentioned, using more GPUs may lead to the `Could not create rings` warning. This warning might be worked around by setting `NCCL_RINGS=0,1,3,2,7,6,4,5,8,9,11,10,15,14,12,13` OR setting `CUDA_VISIBLE_DEVICES=0,1,3,2,7,6,4,5`.

**Comment by cswinter** [comment] 2019-05-11 04:14
Thanks for the suggestions! First time I'm hearing of MPI binding strategies, sounds like got some reading to do 😄. Some of my runs did have `NCCL_NSOCKS_PERTHREAD` > 1 but my tests were far from exhaustive, I'm hoping to find the time for a more thorough sweep next week. Main reason for using 1-GPU is because it is the simplest possible configuration and I've found it to perform better previously, the nodes themselves do have a full 8 GPUs.

**Comment by yaroslavvb** [comment] 2019-05-12 03:22
Glad to see this moving along!
I did some testing with [iperf](https://github.com/cybertronai/bflm/blob/master/infra/iperf_benchmark.py) and [NCCL/PyTorch](https://github.com/cybertronai/bflm/blob/master/infra/pytorch_bandwidth_benchmark.py) on two p3dn.24xlarge using 16 GPUs total to run a training loop on a simple network with 300M parameters (approximating in size the standard model from https://github.com/NVIDIA/Megatron-LM)

using `sudo nload` to check the bandwidth, what I saw

```
iperf3: 92 Gbps
nccl 2.3.7: 41 Gbps
nccl 2.4.6: 10.7 Gbps
nccl 2.4.7ms0: 12.8 Gbps
nccl 2.4.7ms0: 18.4 Gbps    (after removing NCCL_MIN_NRINGS=16 setting)

```

So it seems considerably faster than nccl 2.4.6 provided that NCCL_MIN_RINGS setting is removed.

I don't quite get what nccl 2.3.7 is doing -- it's sending 2x more bits than nccl 2.4.6 when running the same task.  Despite the extra bits, the end-to end step time is still better in old version of nccl -- 187 ms vs 220 ms in 2.4.7ms0

**Comment by kwen2501** [comment] 2019-05-12 05:10
Thanks @yaroslavvb for the feedback! Glad to hear that there is improvement over 2.4.6.

NCCL 2.4 introduces the tree algorithm for inter-node communication, while NCCL 2.3 uses the ring algorithm. That may explain why there is less traffic over the network link in NCCL 2.4.

Regarding the `nload` numbers, I am not sure over which period the numbers are reported. But since a PyTorch application is used, I would assume the period contains both communication and computation (although the period may be shorter than the application run time). I would also assume the bandwidth is averaged over that period. As NCCL 2.4 only sends half as much the traffic, the network **usage** intensity over that period could be lower than 2.3 I think.

If you set `NCCL_TREE_THRESHOLD=0`, NCCL 2.4 will use the ring algorithm again, and you may see again the 2x amount of traffic. 

That said, we would still recommend using [NVIDIA/nccl-tests](https://github.com/NVIDIA/nccl-tests) to measure the bandwidth.

**Comment by cswinter** [comment] 2019-05-16 00:43
Haven't done thorough testing yet, but can confirm that passing `--bind-to none` to mpirun allows the expected number of cores to be used and gives close to optimal busbw on 2node x 1gpu and 4node x 1gpu configurations with 32Gbit/s interconnect and sufficiently large message sizes when setting `-x NCCL_NSOCKS_PERTHREAD=1 -x NCCL_SOCKET_NTHREADS=8`. Performance still degrades to about 50%-60% on the same settings when using 8 GPUs per node.

**Comment by yaroslavvb** [comment] 2019-05-18 06:29
Here's what I'm seeing on AWS with nccl-test after patch for 1280MB allreduce

```
# nThread 1 nGpus 4 minBytes 1342177280 maxBytes 1342177280 step: 2(factor) warmup iters: 5 iters: 20 validation: 1 
#
# Using devices
#   Rank  0 Pid   6435 on ip-172-31-15-234 device  0 [0x00] Tesla V100-SXM2-32GB
#   Rank  1 Pid   6435 on ip-172-31-15-234 device  1 [0x00] Tesla V100-SXM2-32GB
#   Rank  2 Pid   6435 on ip-172-31-15-234 device  2 [0x00] Tesla V100-SXM2-32GB
#   Rank  3 Pid   6435 on ip-172-31-15-234 device  3 [0x00] Tesla V100-SXM2-32GB
#   Rank  4 Pid   6436 on ip-172-31-15-234 device  4 [0x00] Tesla V100-SXM2-32GB
#   Rank  5 Pid   6436 on ip-172-31-15-234 device  5 [0x00] Tesla V100-SXM2-32GB
#   Rank  6 Pid   6436 on ip-172-31-15-234 device  6 [0x00] Tesla V100-SXM2-32GB
#   Rank  7 Pid   6436 on ip-172-31-15-234 device  7 [0x00] Tesla V100-SXM2-32GB
#   Rank  8 Pid   6910 on ip-172-31-3-83 device  0 [0x00] Tesla V100-SXM2-32GB
#   Rank  9 Pid   6910 on ip-172-31-3-83 device  1 [0x00] Tesla V100-SXM2-32GB
#   Rank 10 Pid   6910 on ip-172-31-3-83 device  2 [0x00] Tesla V100-SXM2-32GB
#   Rank 11 Pid   6910 on ip-172-31-3-83 device  3 [0x00] Tesla V100-SXM2-32GB
#   Rank 12 Pid   6911 on ip-172-31-3-83 device  4 [0x00] Tesla V100-SXM2-32GB
#   Rank 13 Pid   6911 on ip-172-31-3-83 device  5 [0x00] Tesla V100-SXM2-32GB
#   Rank 14 Pid   6911 on ip-172-31-3-83 device  6 [0x00] Tesla V100-SXM2-32GB
#   Rank 15 Pid   6911 on ip-172-31-3-83 device  7 [0x00] Tesla V100-SXM2-32GB
#
#                                                     out-of-place                       in-place          
#       size         count    type   redop     time   algbw   busbw  error     time   algbw   busbw  error
#        (B)    (elements)                     (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)       
  1342177280     335544320   float     sum   393849    3.41    6.39  4e-07   393870    3.41    6.39  4e-07
# Out of bounds values : 0 OK
# Avg bus bandwidth    : 6.38954 
#
```

By comparison, before patch, algorithm bandwidth is 1.18, while NCCL 2.3.7 is 0.63


The interesting thing is that `NCCL_MIN_NRINGS` didn't seem to have an effect on nccl-test, for any version of nccl, while in PyTorch it has a significant effect. The host bandwidth (as seen on nload) goes from 10 to 50 Gbps as I increased number of rings between two machines in older version of nccl, whereas nccl-test example goes up to 25 Gbps, and is not affected by rings.

One possible difference from nccl-tests setting is that PyTorch launches multiple nccl allreduces in parallel, so perhaps this sidesteps per-connection limits.

I've instructions to reproduce this benchmark here:
https://github.com/cybertronai/aws-network-benchmarks

**Comment by cswinter** [comment] 2019-06-04 12:42
I was on PTO for a week but I've now had the time for a more thorough look at 2.4.7ms0. The regression from 2.4 seems to be fixed and I have identified configurations that could benefit from further improvements.

## GCP Results

These are my results for allreduce performance on GCP's 32GbE instances:

| bus bandwidth / Gbit/s | nodes | GPUs per node | NSOCKS | NTHREADS | min message size | log |
| --- | --- | --- | --- | --- | --- | --- |
| 30.6, 31.0, 31.4 | 2 | 1 | 1 | 8 | 32MiB | [gist](https://gist.github.com/cswinter/1ee55a12d35e9c45e724d9d2e0e3ab98) |
| **14.5, 14.8, 14.9** | 2 | 8 | 1 | 4 | 64MiB | [gist](https://gist.github.com/cswinter/3e23d5ef2c84d89b25b0b7db277aa050) |
| 30.4, 30.8, 30.8 | 4 | 1 | 2 | 8 | 128MiB | [gist](https://gist.github.com/cswinter/a84b2df787724f8762ca72eab3bd6dc3) |
| **22.2, 22.4, 22.9** | 4 | 8 | 3 | 4 | 128MiB | [gist](https://gist.github.com/cswinter/1cc54dc7700fed9ee5f10a5eb743d9a1) |

When there is one GPU per node the new revision is working great most of the time, but **performance drops significantly when using 8 GPUs per node** (similar to previous revisions). It is unexpected that 2x8gpu nodes should give better performance than 4x8gpu nodes. I've seen this happen on two sets of hosts but it could still just be due to variance tied to different hosts (see below). There's a different anomaly on AWS where using 8 GPUs per node seems to be 20% faster than 1 GPU per node.

I later ran additional benchmarks (I didn't bother with extensive hyperparameter sweeps this time) on a different sets of hosts with identical hardware. They had consistently different performance, and there was some indication that the optimal config was different as well. They did show the same performance degradation going from 1 to 8 GPUs. As far as I could tell, this was with an identical NCCL revision and config and I could not find any issues with the hosts themselves (iperf and my experimental collective communications library got close to 32Gbit/s). I did not check for issues with the GPUs.

Host pair 1:

| bus bandwidth / Gbit/s | nodes | GPUs per node | NSOCKS | NTHREADS | min message size | log |
| --- | --- | --- | --- | --- | --- | --- |
| 11.1, 19.6, 22.5 | 2 | 1 | 1 | 8 | 32MiB | [gist](https://gist.github.com/cswinter/53bd4e59799c898d545ae649f67f518d) |
| 22.5, 24.4, 25.1 | 2 | 8 | 2 | 2 | 32MiB | ^ |
| 14.3, 14.5, 14.8 | 4 | 1 | 1 | 8 | 32MiB | ^ |
| 13.9, 14.7, 14.9 | 4 | 8 | 2 | 2 | 32MiB | ^ |

Host pair 2:

| bus bandwidth / Gbit/s | nodes | GPUs per node | NSOCKS | NTHREADS | min message size | log |
| --- | --- | --- | --- | --- | --- | --- |
| 24.5, 30.4, 31.1 | 2 | 1 | 1 | 8 | 32MiB | [gist](https://gist.github.com/cswinter/f3ab7da0a38d75df955ef85577c29f8d) |
| 14.3, 14.7, 14.8 | 2 | 8 | 1 | 8 | 32MiB | ^ |

**It would be awesome if we could get performance be more consistent across hosts, and 8GPU performance (which is what we really care about) to match that of running with 1GPU.** Also, I don't know whether you have an easy way to acquire 8xV100, 32G GCP hosts but if you do not and would like to use some for development/testing let me know (clemens@openai.com).

## AWS results

I have started doing some preliminary testing on Amazon's p3dn.24xlarge instances that matches Yaroslav's results of ~50Gbit/s. I am still working on getting EFA enabled p3dn.24xlarge instances set up properly though which should give even better performance.

## Additional Notes

Is there a recommended way of running nccl-tests with 8 GPUs per host? I've been using both `-H ip1:8 ip2:8 -np 16 ... -g 1` and `-H ip1:1 ip2:1 -np 2 ... -g 8` and never saw much of a performance difference although P2P connections change from `P2P/IPC` to `P2P/direct pointer`.

One potential confounder on the GCP hosts is the fact that the hardware is capable of more than 32Gbit/s and is artificially constrained by a rate limiter. For sustained usage, this works well but as streams start up network usage might actually exceed 40Gbit/s for a small amount of time before the rate limiter catches up. I took some high resolution network utilization samples with `speedometer` though and the nccl-tests do not seem to run into this.

## Benchmarking Methodology
- Host bw is sanity checked with iperf
- To determine what values for  `NCCL_NSOCKS_PER_THREAD` and `NCCL_SOCKET_NTHREADS` to use I go through the following process:
  - I manually try out various values by running nccl-tests with message sizes from 1M to 128M
  - For this I only look at the “in-place” bandwidth
  - Typically there's a few dozen invocations until I'm sure that I have a set of parameters that is close to optimal
  - There were usually several different configs with similarly high performance
- Once I have determined the parameters, I record the "Avg bus bandwidth" of nccl-tests 3 more times with message sizes between the smallest message size large enough to get optimal performance and 1GB
- To choose the lower message size for final tests, I find the smallest message size that still looks in-distribution for peak performance and then go up by two

**Comment by sjeaugey** [comment] 2019-06-04 16:29
Thanks for the feedback.

Did you set `CUDA_VISIBLE_DEVICES=0,1,3,2,7,6,4,5` on GCP ? If you didn't, that would explain the poor performance with 8 GPUs per node.

Also note, in the special case of two nodes, the bus BW can get up to 2x the network bandwidth with trees. That's due to the fact that the tree organizes the communication in a special way, using internal NVLinks more and inter-node less (1). This does not apply to 3+ nodes.

(1) The total amount to communicate is (n-1)*size. Rings will balance traffic evenly so that each intra-node and inter-node link transmits and receives (n-1)/n*size. Trees are not evenly balanced : each intra-node link will see the full size, while the inter-node link will see only 1/2*size in the two-node case. So we can see a bus BW of up to 2x the network bandwidth, provided the internal NVLink bandwidth can handle the extra 1/n*size.

**Comment by kwen2501** [comment] 2019-06-04 22:13
Hi @cswinter Thanks for the feedback. 

### GCP 32G
Here is the best perf I got from 2 x GCP 32GbE instances with a total of 16 GPUs:

Parameters:
`NCCL_NSOCKS_PERTHREAD=1 NCCL_SOCKET_NTHREADS=4 NCCL_BUFFSIZE=16777216 CUDA_VISIBLE_DEVICES=0,1,3,2,7,6,4,5`

Result:
```#                                                            out-of-place                       in-place
#       size         count    type   redop    root     time   algbw   busbw  error     time   algbw   busbw  error
#        (B)    (elements)                             (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)
   268435456      67108864   float     sum            93219    2.88    5.40    N/A    93181    2.88    5.40    N/A
```
Since the run was on two nodes, the tree algorithm was enabled for all sizes. And as mentioned by @sjeaugey, the bus BW of the tree algorithm may be higher than the network bandwidth. That's why we are seeing 5.4 GB/s rather than 4 GB/s. If I force the ring algorithm (by setting `NCCL_TREE_THRESHOLD=0`), the peak bus BW I got is 3.85 GB/s (also at 256MB message size, 16 GPUs). But similar to what you've mentioned, there could be variations.

In the above run, I've also set `NCCL_BUFFSIZE` to 16MB as compared to 4MB by default. This will increase the network request size for the tree algorithm, which we observed helped the performance in the GCP 32G network. However, the same setting may not have such effect on other networks (e.g. GCP 100G or AWS).

### Benchmarking using iperf
One important thing to know is that only the **bidirectional** iperf performance matches the traffic pattern of NCCL allreduce operations. One can do that by either launching a pair of iperf runs in opposite directions **simultaneously,** or using the `-d` option of iperf2 (may hit crashes sometimes).

**Comment by cswinter** [comment] 2019-06-05 16:08
Did another quick test with `CUDA_VISIBLE_DEVICES` and everything seems to work as expected now 🎉
Will now test whether performance gains carry over to full application, and try to collect more data on host specific performance drops.

Also, could we get nccl or nccl-tests to print out a warning when multiple ranks reuse the same GPU? I suspect this is rarely intended, and even with `NCCL_DEBUG=INFO` I couldn't find any indication that it's happening.

**Comment by sjeaugey** [comment] 2019-06-05 16:19
Awesome. Thanks. I opened #231 to follow up on your request.

**Comment by kwen2501** [comment] 2019-06-05 17:55
For the case of multiple ranks reusing the same GPU (if it indeed goes through initialization successfully), you may be able to notice such usage from the `Init COMPLETE` log that comes with `NCCL_DEBUG=INFO`. 

For example:
```NCCL INFO comm 0x556fe4c70860 rank 3 nranks 16 cudaDev 3 nvmlDev 3 - Init COMPLETE```
And later another line with the same cudaDev but different rank:
```NCCL INFO comm 0x5644e6e34af0 rank 4 nranks 16 cudaDev 3 nvmlDev 3 - Init COMPLETE```

But indeed, this does not distinguish from a (more valid) use case of having multiple communicators, where ranks of different communicators reside on the same GPU. Just providing a quick method to check for the case you described before a fix is in place for #231.

**Comment by cswinter** [comment] 2019-06-20 20:47
I've spent some time this week trying to carry over the performance gains to a real workload and now have early evidence of significant improvements (but still need more testing to confirm).

One issue I've been running into is CPU utilization. With nccl-tests configured for a similar workload, I get good performance with `NCCL_NSOCKS_PERTHREAD=2`, `NCCL_SOCKET_NTHREADS=8` but in the application the same parameters cause 100% cpu utilization and massive performance degradation. Since this is a somewhat complex codebase it's not super easy for me to figure out exactly what is going on, but it *looks* like NCCL might be spawning `NCCL_SOCKET_NTHREADS` threads for each GPU/mpi rank and fully utilizing them even at times when I would expect NCCL to be idle. Is this expected, or should I be looking for a bug somewhere in our code? Is there a way of using NCCL that would avoid this issue and allow me to use the same parameters in my application and in nccl-tests?

Some more info about my workload: It is a large supervised model implemented in tensorflow and trained model-parallel on 4 nodes x 8 gpus. NCCL is used for allreduce of gradients across 32 mpi ranks and is accessed through a wrapper implemented by an internal version of [blocksparse](https://github.com/openai/blocksparse).

**Comment by AddyLaddy** [comment] 2019-06-20 21:00
Are you using Ke's latest patch? https://github.com/NVIDIA/nccl/pull/223/commits/7d03d82b2a30a701b3105ca185412b15fdd8a075

**Comment by kwen2501** [comment] 2019-06-20 21:01
Hi @cswinter , thanks for the feedback. Have you tried the new HEAD of the PR branch? We pushed a new [commit ](https://github.com/NVIDIA/nccl/pull/223/commits/7d03d82b2a30a701b3105ca185412b15fdd8a075)that improves CPU utilization about two weeks ago.

**Comment by cswinter** [comment] 2019-06-20 21:03
Oh perfect, I was still using the previous revision will try with the new one.

**Comment by cswinter** [comment] 2019-06-20 21:17
Can confirm that the CPU utilization issue goes away when using the latest patch.

**Closed** 2019-06-25 21:03 UTC
