### ISSUE TITLE
Warning: too many open files

### ISSUE THREAD

**Issue by lhb8125** [NVIDIA/nccl#127] opened 2018-01-29 11:04 UTC
I want to perform global Batch Normalization in MXNET with NCCL, here I insert nccl codes in BN operator:

`ncclComm_t *commFor
commFor = (ncclComm_t*)malloc(sizeof(ncclComm_t));
NCCLCHECK(ncclCommInitRank(commFor,param_.nGPUs,commUid,devid));
NCCLCHECK(ncclAllReduce((const void*)mean.dptr_,(void*)mean.dptr_,mean.  shape_[0],ncclFloat,ncclSum,*commFor,0));`

By the way, we use pthread to manage multi-process. The result is correct, while when the depth of the network comes to a degree, it will report:

> Socket.h(166):"too many open files"

Sorry, I cannot get the precise error description now. So I increase the max file descriptors:

`ulimits -n 4096`

The error disappears. However, in my codes, I need to allocate new operator many times, so the allocated communicators should be destroyed, so I  do this in destructor:

`ncclCommDestroy(*commFor);`

I am sure the function is invoked because the memory has been released, but the file descriptor still exists, so after several times, it will still report the error:

> Socket.h(166):"too many open files"

I can not increase the max file counts anymore. when I type:

`lsof -p PID`

I get some strange results:

> COMMAND   PID USER   FD      TYPE             DEVICE  SIZE/OFF     NODE NAME
...
python  28867  ttq  130u     IPv4           22106874       0t0      TCP 10.132.*.*:40216 (LISTEN)
python  28867  ttq  131u     IPv4           22140580       0t0      TCP 10.132.*.*:59400 (LISTEN)
python  28867  ttq  132u     IPv4           22114119       0t0      TCP 10.132.*.*:33720 (LISTEN)
python  28867  ttq  133u     IPv4           22155336       0t0      TCP 10.132.*.*:36279 (LISTEN)
python  28867  ttq  134u     IPv4           22141343       0t0      TCP 10.132.*.*:49584 (LISTEN)
python  28867  ttq  136u     IPv4           22114097       0t0      TCP 10.132.*.*:57941 (LISTEN)
...

The count of TCP connections will double when allocating new communicators. Finally, It will exceed the maximum file counts.

I don't know why the file descriptors still exist after I destroy the communicator?

**Comment by sjeaugey** [comment] 2018-09-26 18:14
It looks like you are calling ncclGetUniqueId on *all* ranks for every communicator you create. It should only be called on *one* rank (then passed to others).

**Comment by sjeaugey** [comment] 2018-09-27 16:15
OK, so if you are calling ncclGetUniqueId only once per nranks calls to ncclCommInitRank/ncclCommDestroy, it would be good to see if you can still see the issue with the latest version and provide a reproducer. Also, it could just be due to the fact that you have too many communicators.

Aside from that, it is in general discouraged to create/destroy a lot of NCCL communicators. Many reasons for that :

 - calls to ncclCommInit are expensive (and we try to put as much as we can in those functions to accelerate communication calls later).
 - launching collective operations on multiple NCCL communicators in parallel can randomly hang if not carefully ordered (which usually defeats the purpose of having multiple NCCL communicators).
 - creating one communicator per layer in a DL case means a lot of small reductions which is usually quite inefficient. Most frameworks are now doing some aggregation through a communication component on the side (e.g. Horovod).

**Comment by sjeaugey** [comment] 2019-05-06 23:46
Closing old bug. Feel free to reopen if it is still an issue.

**Closed by sjeaugey** 2019-05-06 23:46 UTC
