### ISSUE TITLE
NCCL memcpy time

### ISSUE THREAD

**Issue by sj6077** [NVIDIA/nccl#213] opened 2019-04-24 11:49 UTC
I want to make a log for the memcpy time of NCCL communication such as GPU-> CPU or GPU->GPU. I looked over the source codes but I couldn't find a good place to make a log inside. Can you let me know which part is related to the memcpy time?

**Comment by kwen2501** [comment] 2019-04-24 15:33
Hi,
NCCL is based on SM writes rather than copy engines. That said, the data transfer in NCCL does not rely on the cudaMemcpy API.

**Comment by sj6077** [comment] 2019-04-24 16:09
Can you let me know the code for where SM write happens?

**Comment by sjeaugey** [comment] 2019-04-24 16:52
It happens in many places depending on the protocol, like in Store128() : https://github.com/NVIDIA/nccl/blob/master/src/collectives/device/common_kernel.h#L245.

So it is not a "memcpy" time, but a "ReduceOrCopy" time (https://github.com/NVIDIA/nccl/blob/master/src/collectives/device/common_kernel.h#L319) which does much more than copying data. Also, this function is used for each chunk of data and can be called many times for a single collective operation.

**Comment by sj6077** [comment] 2019-04-25 02:48
Thanks for your help!

**Comment by sj6077** [comment] 2019-04-25 06:22
I have one more question. I checked that ReduceOrCopy calls store or load for data movement. 
I assume that the data movement in store/load is always related to intra-communication. Is that right?
Moreover, I want to know the src and destination devices instead of just pointers. Can you also give me a tip to find the information?

**Comment by AddyLaddy** [comment] 2019-04-25 16:29
The NCCL CUDA kernels always just store/load to memory either GPU memory or host memory. For inter-node communication Linux proxy threads poll host memory and then transfer the data using the network making us of GDRDMA when available. Hence the NCCL CUDA kernels are unaware of the network hops or proxies.

**Comment by sj6077** [comment] 2019-05-01 14:07
How can you distinguish which one is copied to GPU memory and which is not(to/from CPU)? Maybe a reduction function also can be performed either CPU or GPU but it's hard to distinguish in the code.

**Comment by sjeaugey** [comment] 2019-05-01 17:19
It's not easy. By design, the kernel does not know where it's writing data too.

It could be the next GPU directly, could ne shared memory, could be system memory for the network, or its own device memory when using GPU Direct RDMA.

**Comment by sjeaugey** [comment] 2020-04-15 00:43
Closing as this seems to be resolved. Please re-open if needed.

**Closed by sjeaugey** 2020-04-15 00:43 UTC

**Comment by mabdullahsoyturk** [comment] 2021-05-01 11:43
> The NCCL CUDA kernels always just store/load to memory either GPU memory or host memory. For inter-node communication Linux proxy threads poll host memory and then transfer the data using the network making us of GDRDMA when available. Hence the NCCL CUDA kernels are unaware of the network hops or proxies.

Sorry for opening this issue after a long time but where does this Linux proxy thread polling operation happen in the code? I couldn't manage to find it.

**Comment by jiangxiaobin96** [comment] 2023-09-12 09:14
> It happens in many places depending on the protocol, like in Store128() : https://github.com/NVIDIA/nccl/blob/master/src/collectives/device/common_kernel.h#L245.
> 
> So it is not a "memcpy" time, but a "ReduceOrCopy" time (https://github.com/NVIDIA/nccl/blob/master/src/collectives/device/common_kernel.h#L319) which does much more than copying data. Also, this function is used for each chunk of data and can be called many times for a single collective operation.


`Store128` store the 128bit value to dsts. If dsts ptr points to another GPU memory, how to transfer data? Do dst ptr also point to UVA and gpu A can directly read/write gpu B by UVA?

**Comment by jbachan** [comment] 2023-09-12 09:32
> > It happens in many places depending on the protocol, like in Store128() : https://github.com/NVIDIA/nccl/blob/master/src/collectives/device/common_kernel.h#L245.
> > So it is not a "memcpy" time, but a "ReduceOrCopy" time (https://github.com/NVIDIA/nccl/blob/master/src/collectives/device/common_kernel.h#L319) which does much more than copying data. Also, this function is used for each chunk of data and can be called many times for a single collective operation.
> 
> `Store128` store the 128bit value to dsts. If dsts ptr points to another GPU memory, how to transfer data? Do dst ptr also point to UVA and gpu A can directly read/write gpu B by UVA?

In many cases GPUs can load and store to each others memory, which we detect from the CPU before hand. If they cannot, then we allocate the memory as CUDA host memory which both GPUs can access. Either way, the GPU code can just assume it can access the memory.

**Comment by jiangxiaobin96** [comment] 2023-09-12 09:37
each GPU has its own address, how to distinguish dst belong to which gpu without UVA.
