### ISSUE TITLE
 Consultation on performance degradation in multi-node parallel training on NCCL 2.3.5

### ISSUE THREAD

**Issue by heweijia02** [NVIDIA/nccl#173] opened 2018-12-21 09:20 UTC
In NCCL version 2.3.5, when we were doing multi-node parallel training. When the number of nodes exceeds 6, performance degradation occurs. When the NCCL version is rolled back to 2.1.5, the performance returns to normal. Each of our nodes contains 8 V100 GPUs (16GB).
We checked our environment and found that when using NCCL 2.3.5, the server NIC will send a pause frame. When using NCCL 2.1.5, the problem disappears. We are using the Roce protocol. I understand that NCCL uses circular traffic. Normally, there should be no Pause frames. Unless the NCCL reads data from the network card at a slower rate than the NCCL's ring input speed. Since we don't have the NCCL 2.1.5 code, it's unclear what 2.3.5 has changed. But obviously this is because of the problems introduced by the NCCL version. So I want to consult you, what is the cause of the problem? How to circumvent this problem in version 2.3.5? Or did you fix this on the latest 2.3.7 version?

**Comment by sjeaugey** [comment] 2018-12-21 17:09
I ran a diff against 2.1.5 and the only difference concerning how we configure RoCE concerns RNR packets.  I doubt it will make a difference, since RNRs should not happen by design, but feel free to modify `src/transport/net_ib.cu` to make rnr_timer = rnr_retry = 1 as it was in 2.1.5 (instead of respectively 12 and 7 now) to make sure it's not related to that (unless packet drops are also handled by RNR timers).

Also, this could be a timing and configuration issue. With RoCE, if you happen to get collisions, performance will drastically drop. You might see a performance drop with a new version that has slightly different timings. I suggest you work with your RoCE switch provider to configure your RoCE switches in lossless mode for the NCCL traffic (you might want to keep your TCP/IP traffic on a different VLAN in loss mode). That usually solves RoCE performance problems, though the precise configuration is vendor dependent.

**Comment by heweijia02** [comment] 2019-01-07 08:03
Dear sjeaugey ,
         First of all, I have to correct my previous description. When I tested on nccl 2.3.5, I found a lot of pause frames on the NIC. I didn't find the pause frame on the nccl 2.1.15 test. Rather than the previously described nccl 2.1.5.
         At the same time, I conducted the following test, using 2 servers, each with 8 V100 GPUs.
           1）NCCL 2.3.5+CUDA 9.2（CUDNN 7.2.1）+tensorflow 1.10.1+MPI 3.1.2     Pause Frames found
           2）NCCL 2.3.7+CUDA 9.2（CUDNN 7.2.1）+tensorflow 1.10.1+MPI 3.1.2     Pause Frames found
           3）NCCL 2.1.15+CUDA 9.0（CUDNN 7.0.5）+tensorflow 1.10.0+MPI 3.0.0   No Pause Frames
          4 )  NCCL 2.3.5+CUDA 9.0（CUDNN 7.0.5）+tensorflow 1.10.0+MPI 3.0.0      Pause Frames found
          5 )  NCCL 2.3.7+CUDA 9.0（CUDNN 7.0.5）+tensorflow 1.10.0+MPI 3.0.0      Pause Frames found
          6 )  NCCL 2.3.5(rnr_timer = rnr_retry = 1)+CUDA 9.0（CUDNN 7.0.5）+tensorflow 1.10.0+MPI 3.0.0      Pause Frames found
         1)~5)The NCCL version used in the test is the version you released directly.
         6) The version of nccl used is the code you posted in 2.3.5. I modified the recompiled version after RNR according to your previous suggestions.
         We also consulted Mellanox FAE, which they thought was a problem with software calls. What do you think?

**Comment by sjeaugey** [comment] 2019-01-08 17:45
What is the performance difference between the two versions ? As far as I understand, pause frames should be regulating the flow and make performance more stable.

In any case, NCCL, unless there is a bug, doesn't do anything fancy and uses the IB interface to send and receive chunks of 1MB (by default, see the NCCL_BUFFSIZE environment variable).

Note you might want to set the service level (NCCL_IB_SL) and the traffic class (NCCL_IB_TC), which we added upon request from different RoCE vendors (although I guess the usage of those fields varies by vendor and needs to be consistent with the switch configuration).

**Comment by heweijia02** [comment] 2019-01-18 01:04
When I used nccl-test for testing, NCCL2.1.15+CUDA9.0+MPI3.0.0 also produced a large number of pause frames. The specific commands are as follows: mpirun --prefix /usr/local/openmpi --mca btl_tcp_if_include enp165s0f1 -np 2 -H 192.168.5.177:1,192.168.5.180:1 -x NCCL_IB_HCA=mlx5_5:1 -x NCCL_IB_DISABLE=0 -x NCCL_DEBUG=INFO -x NCCL_MAX_NRINGS=1 -x NCCL_SOCKET_IFNAME=enp165s0f1 -x LD_LIBRARY_PATH ./build/all_reduce_perf -b 512K -e 512K -f 1 -g 1 -c 0 -d all -o sum -n 1 -w 0 -d float

I did the same experiment on NCCL 2.3.5. Our ROCE developers communicated with me that after creating QP, you should add multiple rwqes to RWQ instead of just adding one rwqe. They think that when only one is added, the send operation and write with IMM will cause the consumption of rwqe. This may cause the pause frame to be generated before the new rwqe is generated. What do you think?

**Comment by heweijia02** [comment] 2019-01-18 01:36
我添加了一些打印日志，我发现，你们确实每次下发了4个rwqe，但同时你们会有4个wirte操作和4个write with imm操作，4个write with imm会消耗掉4个rwqe。如下是其中一台服务器上的日志：
netRecvProxy coming:llMode=0,ring->buffSize=4194304,args->substeps=4,llBufSize=65536
netRecvProxy------>ncclNetIrecv,sliceSize=1048576
netSendProxy coming:llMode=0,ring->buffSize=4194304,args->substeps=4,llBufSize=65536
netSendProxy------>2,ncclNetIsend,size=65536
wrap_ibv_post_recv------------>1,qp=60735560
,wrap_ibv_post_send------------>1,opcode=0,qp=60735560
netRecvProxy------>ncclNetIrecv,sliceSize=1048576
wrap_ibv_post_recv------------>1,qp=60735560
,wrap_ibv_post_send------------>1,opcode=0,qp=60735560
netRecvProxy------>ncclNetIrecv,sliceSize=1048576
wrap_ibv_post_recv------------>1,qp=60735560
,wrap_ibv_post_send------------>1,opcode=0,qp=60735560
netRecvProxy------>ncclNetIrecv,sliceSize=1048576
wrap_ibv_post_recv------------>1,qp=60735560
,wrap_ibv_post_send------------>1,opcode=0,qp=60735560
wrap_ibv_post_send------------>1,opcode=1,qp=60712904
netSendProxy------>2,ncclNetIsend,size=0
wrap_ibv_post_send------------>1,opcode=1,qp=60712904
netSendProxy------>2,ncclNetIsend,size=65536
wrap_ibv_post_send------------>1,opcode=1,qp=60712904
netSendProxy------>2,ncclNetIsend,size=0
wrap_ibv_post_send------------>1,opcode=1,qp=60712904

**Comment by sjeaugey** [comment] 2019-01-18 01:43
Yes, we always post receive requests which match a soon-to-come send. So the number of send and receive always match, and when the collective is complete, no receive is posted. That's by design.

**Comment by sjeaugey** [comment] 2019-01-18 01:48
One precision, the ibv_post_send posted on the receive side (the write ones) are the writes to tell the sender it can proceed. Those do not consume any receive WQE and are targeting a FIFO on the sender side, simply writing to it. The write_with_imm sends are the ones consuming the receive WQEs.

**Comment by heweijia02** [comment] 2019-01-18 01:49
Then I have such a concern, if there are 2 servers, each server's qp is sending rwqe and swqe through the thread. If one side is fast, it is slow. Does that trigger this problem?

**Comment by heweijia02** [comment] 2019-01-18 01:59
Our ROCE developers describe the process of creating pause frames. Node1 and node2 create QP_1 and QP_2, respectively, and start the send thread and the receive thread respectively. The node1 thread runs faster than the node2 block. When node1 sends send with imm and send operations to node2, node2's rwqe has not been created successfully. At this point wite with imm will stay in the queue, causing the data of wite to stay in the queue. As a result, the data of the network card is accumulated, which in turn causes a pause frame. Do you think this will happen?

**Comment by sjeaugey** [comment] 2019-01-18 02:09
No, that should not happen. We have the FIFO between the receiver and the sender to exactly avoid that. On Infiniband that scenario would cause RNR Nacks which would also be very bad for latency. That's why we have that FIFO so that every Send is started only when the matching Receive has already been posted.

**Comment by sjeaugey** [comment] 2019-05-06 23:51
Closing old bug. Feel free to reopen if you have further questions.

**Closed by sjeaugey** 2019-05-06 23:51 UTC
